# Generated by Django 5.0.6 on 2024-07-03 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_best'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='best',
            name='category',
        ),
    ]
