# Generated by Django 5.0.6 on 2024-07-03 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_best_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='best',
            old_name='icon',
            new_name='image',
        ),
    ]
